--------------------------------------------------------
--  Arquivo criado - Quarta-feira-Setembro-18-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AM_USUARIO
--------------------------------------------------------

  CREATE TABLE "RM83088"."AM_USUARIO" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"NOME" VARCHAR2(30 BYTE), 
	"SOBRENOME" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"RM" VARCHAR2(6 BYTE), 
	"SENHA" VARCHAR2(30 BYTE), 
	"RESPOSTASEGURANCA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
REM INSERTING into RM83088.AM_USUARIO
SET DEFINE OFF;
Insert into RM83088.AM_USUARIO (ID_USUARIO,NOME,SOBRENOME,EMAIL,RM,SENHA,RESPOSTASEGURANCA) values ('2','renan','camargo','rene.camargo@gmail.com','987456','y98ee3hf3256','abc');
Insert into RM83088.AM_USUARIO (ID_USUARIO,NOME,SOBRENOME,EMAIL,RM,SENHA,RESPOSTASEGURANCA) values ('3','roberta','de Camargo','beta.rbm@gmail.com','123654','asdf','asdf');
Insert into RM83088.AM_USUARIO (ID_USUARIO,NOME,SOBRENOME,EMAIL,RM,SENHA,RESPOSTASEGURANCA) values ('1','Raphael','de Camargo','raphaelcamar@outlook.com','83088','y98ee3hf','a mumia');
--------------------------------------------------------
--  DDL for Index SYS_C006940020
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM83088"."SYS_C006940020" ON "RM83088"."AM_USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  Constraints for Table AM_USUARIO
--------------------------------------------------------

  ALTER TABLE "RM83088"."AM_USUARIO" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
